# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_qmt_main(object):
    def setupUi(self, qmt_main):
        qmt_main.setObjectName("qmt_main")
        qmt_main.resize(1000, 700)
        qmt_main.setMinimumSize(QtCore.QSize(1000, 700))
        qmt_main.setWindowTitle("QMT - Quality Magnet Tool")
        self._centralwidget = QtWidgets.QWidget(qmt_main)
        self._centralwidget.setObjectName("_centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self._centralwidget)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self._widget = QtWidgets.QWidget(self._centralwidget)
        self._widget.setObjectName("_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self._widget)
        self.horizontalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.led_label = LEDLabel(self._widget)
        self.led_label.setText("")
        self.led_label.setPixmap(QtGui.QPixmap(":/pixmaps/gray_led"))
        self.led_label.setObjectName("led_label")
        self.horizontalLayout_4.addWidget(self.led_label)
        self.current_block_counter = SyncBlockLabel(self._widget)
        self.current_block_counter.setObjectName("current_block_counter")
        self.horizontalLayout_4.addWidget(self.current_block_counter)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.qmt_logo = QtWidgets.QLabel(self._widget)
        self.qmt_logo.setText("")
        self.qmt_logo.setPixmap(QtGui.QPixmap(":/pixmaps/qmc_logo"))
        self.qmt_logo.setObjectName("qmt_logo")
        self.horizontalLayout_4.addWidget(self.qmt_logo)
        self.verticalLayout_2.addWidget(self._widget)
        self._tabWidget = QtWidgets.QTabWidget(self._centralwidget)
        self._tabWidget.setUsesScrollButtons(False)
        self._tabWidget.setObjectName("_tabWidget")
        self.search_torrent_tab = SearchTorrentsTab()
        self.search_torrent_tab.setObjectName("search_torrent_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.search_torrent_tab)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self._widget_3 = QtWidgets.QWidget(self.search_torrent_tab)
        self._widget_3.setObjectName("_widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self._widget_3)
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self._label_5 = QtWidgets.QLabel(self._widget_3)
        self._label_5.setObjectName("_label_5")
        self.horizontalLayout_2.addWidget(self._label_5)
        self.search_bar = TorrentSearchBar(self._widget_3)
        self.search_bar.setObjectName("search_bar")
        self.horizontalLayout_2.addWidget(self.search_bar)
        self.regex_checkbox = QtWidgets.QCheckBox(self._widget_3)
        self.regex_checkbox.setObjectName("regex_checkbox")
        self.horizontalLayout_2.addWidget(self.regex_checkbox)
        self.search_button = QtWidgets.QPushButton(self._widget_3)
        self.search_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pixmaps/refresh"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_2.addWidget(self.search_button)
        self.budget_projection_btn = QtWidgets.QPushButton(self._widget_3)
        self.budget_projection_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pixmaps/list"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.budget_projection_btn.setIcon(icon1)
        self.budget_projection_btn.setObjectName("budget_projection_btn")
        self.horizontalLayout_2.addWidget(self.budget_projection_btn)
        self.select_masternodes_btn = QtWidgets.QPushButton(self._widget_3)
        self.select_masternodes_btn.setObjectName("select_masternodes_btn")
        self.horizontalLayout_2.addWidget(self.select_masternodes_btn)
        self.masternodes_selected = QtWidgets.QLabel(self._widget_3)
        self.masternodes_selected.setObjectName("masternodes_selected")
        self.horizontalLayout_2.addWidget(self.masternodes_selected)
        self.mn_count_label = QtWidgets.QLabel(self._widget_3)
        self.mn_count_label.setObjectName("mn_count_label")
        self.horizontalLayout_2.addWidget(self.mn_count_label)
        self.hide_expiring_checkbtn = QtWidgets.QPushButton(self._widget_3)
        self.hide_expiring_checkbtn.setCheckable(True)
        self.hide_expiring_checkbtn.setChecked(False)
        self.hide_expiring_checkbtn.setObjectName("hide_expiring_checkbtn")
        self.horizontalLayout_2.addWidget(self.hide_expiring_checkbtn)
        self.verticalLayout_3.addWidget(self._widget_3)
        self.torrents_table = TorrentsTable(self.search_torrent_tab)
        self.torrents_table.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.torrents_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.torrents_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.torrents_table.setRowCount(0)
        self.torrents_table.setObjectName("torrents_table")
        self.torrents_table.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.torrents_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.torrents_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.torrents_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.torrents_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.torrents_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.torrents_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.torrents_table.setHorizontalHeaderItem(6, item)
        self.torrents_table.horizontalHeader().setSortIndicatorShown(True)
        self.torrents_table.horizontalHeader().setStretchLastSection(True)
        self.torrents_table.verticalHeader().setVisible(False)
        self.torrents_table.verticalHeader().setHighlightSections(False)
        self.verticalLayout_3.addWidget(self.torrents_table)
        self._widget_5 = QtWidgets.QWidget(self.search_torrent_tab)
        self._widget_5.setObjectName("_widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self._widget_5)
        self.horizontalLayout_5.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.random_delay_checkbox = QtWidgets.QCheckBox(self._widget_5)
        self.random_delay_checkbox.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pixmaps/clock"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.random_delay_checkbox.setIcon(icon2)
        self.random_delay_checkbox.setObjectName("random_delay_checkbox")
        self.horizontalLayout_5.addWidget(self.random_delay_checkbox)
        self.min_time_numbox = QtWidgets.QSpinBox(self._widget_5)
        self.min_time_numbox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.min_time_numbox.setMaximum(18000)
        self.min_time_numbox.setObjectName("min_time_numbox")
        self.horizontalLayout_5.addWidget(self.min_time_numbox)
        self.max_time_numbox = QtWidgets.QSpinBox(self._widget_5)
        self.max_time_numbox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.max_time_numbox.setMaximum(18000)
        self.max_time_numbox.setProperty("value", 300)
        self.max_time_numbox.setObjectName("max_time_numbox")
        self.horizontalLayout_5.addWidget(self.max_time_numbox)
        spacerItem1 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.torrents_selected_counter = TorrentsSelectedLabelCounter(self._widget_5)
        self.torrents_selected_counter.setObjectName("torrents_selected_counter")
        self.horizontalLayout_5.addWidget(self.torrents_selected_counter)
        self._label_6 = QtWidgets.QLabel(self._widget_5)
        self._label_6.setMaximumSize(QtCore.QSize(25, 25))
        self._label_6.setText("")
        self._label_6.setPixmap(QtGui.QPixmap(":/pixmaps/question"))
        self._label_6.setScaledContents(True)
        self._label_6.setObjectName("_label_6")
        self.horizontalLayout_5.addWidget(self._label_6)
        self.verticalLayout_3.addWidget(self._widget_5)
        self._widget_4 = QtWidgets.QWidget(self.search_torrent_tab)
        self._widget_4.setObjectName("_widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self._widget_4)
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.vote_good_btn = QtWidgets.QPushButton(self._widget_4)
        self.vote_good_btn.setObjectName("vote_good_btn")
        self.horizontalLayout_3.addWidget(self.vote_good_btn)
        self.vote_bad_btn = QtWidgets.QPushButton(self._widget_4)
        self.vote_bad_btn.setObjectName("vote_bad_btn")
        self.horizontalLayout_3.addWidget(self.vote_bad_btn)
        self.verticalLayout_3.addWidget(self._widget_4)
        self._tabWidget.addTab(self.search_torrent_tab, "")
        self.add_torrents_tab = AddTorrentsTab()
        self.add_torrents_tab.setObjectName("add_torrents_tab")
        self.formLayout = QtWidgets.QFormLayout(self.add_torrents_tab)
        self.formLayout.setContentsMargins(9, 9, 9, 9)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self._label = QtWidgets.QLabel(self.add_torrents_tab)
        self._label.setObjectName("_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self._label)
        self.file_name_edit = QtWidgets.QLineEdit(self.add_torrents_tab)
        self.file_name_edit.setObjectName("file_name_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.file_name_edit)
        self._label_2 = QtWidgets.QLabel(self.add_torrents_tab)
        self._label_2.setObjectName("_label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self._label_2)
        self.magnet_uri_edit = QtWidgets.QLineEdit(self.add_torrents_tab)
        self.magnet_uri_edit.setObjectName("magnet_uri_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.magnet_uri_edit)
        self._label_3 = QtWidgets.QLabel(self.add_torrents_tab)
        self._label_3.setObjectName("_label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self._label_3)
        self.qmc_payment_address_edit = QtWidgets.QLineEdit(self.add_torrents_tab)
        self.qmc_payment_address_edit.setObjectName("qmc_payment_address_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.qmc_payment_address_edit)
        self._label_4 = QtWidgets.QLabel(self.add_torrents_tab)
        self._label_4.setObjectName("_label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self._label_4)
        self.category_box = QtWidgets.QComboBox(self.add_torrents_tab)
        self.category_box.setObjectName("category_box")
        self.category_box.addItem("")
        self.category_box.addItem("")
        self.category_box.addItem("")
        self.category_box.addItem("")
        self.category_box.addItem("")
        self.category_box.addItem("")
        self.category_box.addItem("")
        self.category_box.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.category_box)
        self.submit_button = QtWidgets.QPushButton(self.add_torrents_tab)
        self.submit_button.setObjectName("submit_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.submit_button)
        self._label_7 = QtWidgets.QLabel(self.add_torrents_tab)
        self._label_7.setTextFormat(QtCore.Qt.RichText)
        self._label_7.setObjectName("_label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self._label_7)
        self._tabWidget.addTab(self.add_torrents_tab, "")
        self.verticalLayout_2.addWidget(self._tabWidget)
        self._groupBox = QtWidgets.QGroupBox(self._centralwidget)
        self._groupBox.setObjectName("_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self._groupBox)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self._widget_2 = QtWidgets.QWidget(self._groupBox)
        self._widget_2.setObjectName("_widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self._widget_2)
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.console_hide_checkbtn = QtWidgets.QPushButton(self._widget_2)
        self.console_hide_checkbtn.setCheckable(True)
        self.console_hide_checkbtn.setObjectName("console_hide_checkbtn")
        self.horizontalLayout.addWidget(self.console_hide_checkbtn)
        self.console_save_btn = QtWidgets.QPushButton(self._widget_2)
        self.console_save_btn.setObjectName("console_save_btn")
        self.horizontalLayout.addWidget(self.console_save_btn)
        self.console_clean_btn = QtWidgets.QPushButton(self._widget_2)
        self.console_clean_btn.setObjectName("console_clean_btn")
        self.horizontalLayout.addWidget(self.console_clean_btn)
        spacerItem2 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.update_status_label = UpdateLabel(self._widget_2)
        self.update_status_label.setObjectName("update_status_label")
        self.horizontalLayout.addWidget(self.update_status_label)
        self.check_updates_btn = CheckUpdatesButton(self._widget_2)
        self.check_updates_btn.setFlat(False)
        self.check_updates_btn.setObjectName("check_updates_btn")
        self.horizontalLayout.addWidget(self.check_updates_btn)
        self.verticalLayout.addWidget(self._widget_2)
        self.console_log_output = ConsoleLogOutput(self._groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 84, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 28, 28))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 28, 28))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 84, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 28, 28))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 28, 28))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 28, 28))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 84, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 28, 28))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 28, 28))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 28, 28))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.console_log_output.setPalette(palette)
        self.console_log_output.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.console_log_output.setReadOnly(True)
        self.console_log_output.setObjectName("console_log_output")
        self.verticalLayout.addWidget(self.console_log_output)
        self.verticalLayout_2.addWidget(self._groupBox)
        qmt_main.setCentralWidget(self._centralwidget)
        self._menubar = QtWidgets.QMenuBar(qmt_main)
        self._menubar.setGeometry(QtCore.QRect(0, 0, 1000, 18))
        self._menubar.setObjectName("_menubar")
        self._menuSetup = QtWidgets.QMenu(self._menubar)
        self._menuSetup.setObjectName("_menuSetup")
        qmt_main.setMenuBar(self._menubar)
        self.statusbar = QtWidgets.QStatusBar(qmt_main)
        self.statusbar.setObjectName("statusbar")
        qmt_main.setStatusBar(self.statusbar)
        self.rpc_settings_action = QtWidgets.QAction(qmt_main)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pixmaps/qmc_shield"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rpc_settings_action.setIcon(icon3)
        self.rpc_settings_action.setObjectName("rpc_settings_action")
        self.import_masterconf_action = QtWidgets.QAction(qmt_main)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pixmaps/script"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.import_masterconf_action.setIcon(icon4)
        self.import_masterconf_action.setObjectName("import_masterconf_action")
        self._menuSetup.addAction(self.rpc_settings_action)
        self._menuSetup.addAction(self.import_masterconf_action)
        self._menubar.addAction(self._menuSetup.menuAction())
        self._label_5.setBuddy(self.search_bar)
        self._label.setBuddy(self.file_name_edit)
        self._label_2.setBuddy(self.magnet_uri_edit)
        self._label_3.setBuddy(self.qmc_payment_address_edit)
        self._label_4.setBuddy(self.category_box)

        self.retranslateUi(qmt_main)
        self._tabWidget.setCurrentIndex(1)
        self.console_clean_btn.clicked.connect(self.console_log_output.clear)
        self.check_updates_btn.clicked.connect(self.update_status_label.check_updates)
        self.update_status_label.update_checked.connect(self.check_updates_btn.reset_text)
        self.check_updates_btn.clicked.connect(self.check_updates_btn.set_double_dash)
        self.current_block_counter.sync_started.connect(self.led_label.set_green_led)
        self.current_block_counter.sync_finished.connect(self.led_label.set_green_led)
        self.current_block_counter.sync_lost.connect(self.led_label.set_gray_led)
        self.current_block_counter.sync_started.connect(self.current_block_counter.set_synchronizing_status)
        self.current_block_counter.sync_lost.connect(self.current_block_counter.set_unsynced_status)
        self.current_block_counter.sync_finished.connect(self.current_block_counter.set_synced_status)
        self.search_button.clicked.connect(self.search_bar.do_search)
        self.search_bar.search_signal.connect(self.torrents_table.clear)
        self.search_bar.search_signal.connect(self.torrents_table.update_torrents)
        self.console_hide_checkbtn.toggled['bool'].connect(self.console_log_output.setHidden)
        self.torrents_table.itemSelectionChanged.connect(self.torrents_selected_counter.update_counter)
        self.hide_expiring_checkbtn.toggled['bool'].connect(self.torrents_table.show_expiring)
        self.vote_good_btn.clicked.connect(self.torrents_table.vote_selected_good)
        self.vote_bad_btn.clicked.connect(self.torrents_table.vote_selected_bad)
        self.budget_projection_btn.clicked.connect(qmt_main.show_budget_projection)
        self.select_masternodes_btn.clicked.connect(qmt_main.show_masternode_selection)
        self.console_save_btn.clicked.connect(self.console_log_output.save_log)
        self.search_bar.returnPressed.connect(self.search_bar.do_search)
        QtCore.QMetaObject.connectSlotsByName(qmt_main)

    def retranslateUi(self, qmt_main):
        _translate = QtCore.QCoreApplication.translate
        self.current_block_counter.setText(_translate("qmt_main", "0 (unsynced)"))
        self._label_5.setText(_translate("qmt_main", "<b>Search:</b>"))
        self.regex_checkbox.setText(_translate("qmt_main", "Regex?"))
        self.select_masternodes_btn.setText(_translate("qmt_main", "Select Masternodes..."))
        self.masternodes_selected.setText(_translate("qmt_main", "<html><head/><body><p><span style=\" font-weight:600;\">0 </span><span style=\" font-style:italic;\">masternodes selected for voting</span></p></body></html>"))
        self.mn_count_label.setText(_translate("qmt_main", "<html><head/><body><p>Total MN Count: <span style=\" font-style:italic;\">107</span></p></body></html>"))
        self.hide_expiring_checkbtn.setText(_translate("qmt_main", "Hide expiring"))
        self.torrents_table.setSortingEnabled(True)
        item = self.torrents_table.horizontalHeaderItem(0)
        item.setText(_translate("qmt_main", "Name"))
        item = self.torrents_table.horizontalHeaderItem(1)
        item.setText(_translate("qmt_main", "Stream"))
        item = self.torrents_table.horizontalHeaderItem(2)
        item.setText(_translate("qmt_main", "Download"))
        item = self.torrents_table.horizontalHeaderItem(3)
        item.setText(_translate("qmt_main", "QMC/Month"))
        item = self.torrents_table.horizontalHeaderItem(4)
        item.setText(_translate("qmt_main", "Payments"))
        item = self.torrents_table.horizontalHeaderItem(5)
        item.setText(_translate("qmt_main", "Votes"))
        item = self.torrents_table.horizontalHeaderItem(6)
        item.setText(_translate("qmt_main", "SE/LE"))
        self.min_time_numbox.setSuffix(_translate("qmt_main", " secs"))
        self.min_time_numbox.setPrefix(_translate("qmt_main", "- "))
        self.max_time_numbox.setSuffix(_translate("qmt_main", " secs"))
        self.max_time_numbox.setPrefix(_translate("qmt_main", "+ "))
        self.torrents_selected_counter.setText(_translate("qmt_main", "<html><head/><body><p><span style=\" font-style:italic;\">0 torrents selected</span></p></body></html>"))
        self.vote_good_btn.setText(_translate("qmt_main", "Vote Good!"))
        self.vote_bad_btn.setText(_translate("qmt_main", "Vote Bad!"))
        self._tabWidget.setTabText(self._tabWidget.indexOf(self.search_torrent_tab), _translate("qmt_main", "Search Torrents"))
        self._label.setText(_translate("qmt_main", "File Name:"))
        self._label_2.setText(_translate("qmt_main", "Magnet URI:"))
        self._label_3.setText(_translate("qmt_main", "QMC Payment Address:"))
        self._label_4.setText(_translate("qmt_main", "Category: "))
        self.category_box.setItemText(0, _translate("qmt_main", "Video"))
        self.category_box.setItemText(1, _translate("qmt_main", "Audio"))
        self.category_box.setItemText(2, _translate("qmt_main", "App"))
        self.category_box.setItemText(3, _translate("qmt_main", "Game"))
        self.category_box.setItemText(4, _translate("qmt_main", "eBook"))
        self.category_box.setItemText(5, _translate("qmt_main", "Document"))
        self.category_box.setItemText(6, _translate("qmt_main", "Leak"))
        self.category_box.setItemText(7, _translate("qmt_main", "Other"))
        self.submit_button.setText(_translate("qmt_main", "Submit Torrent"))
        self._label_7.setText(_translate("qmt_main", "<html><head/><body><p>Submission requires <span style=\" font-weight:600;\">3</span> confirmations to process.</p><p><span style=\" font-weight:600;\">Do not</span> close this tool until 3 blocks pass since your last submission!</p><p><br/></p><p>Also be aware that this function is beta stage.</p></body></html>"))
        self._tabWidget.setTabText(self._tabWidget.indexOf(self.add_torrents_tab), _translate("qmt_main", "Add Torrents"))
        self._groupBox.setTitle(_translate("qmt_main", "Console Log"))
        self.console_hide_checkbtn.setText(_translate("qmt_main", "Hide"))
        self.console_save_btn.setText(_translate("qmt_main", "Save"))
        self.console_clean_btn.setText(_translate("qmt_main", "Clear"))
        self.update_status_label.setText(_translate("qmt_main", "You have the latest version of QMT"))
        self.check_updates_btn.setText(_translate("qmt_main", "Check QMT version"))
        self.console_log_output.setHtml(_translate("qmt_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Logging</p></body></html>"))
        self._menuSetup.setTitle(_translate("qmt_main", "Setup"))
        self.rpc_settings_action.setText(_translate("qmt_main", "RPC Settings"))
        self.import_masterconf_action.setText(_translate("qmt_main", "Import \"masternode.conf\" file"))

from add_torrents_logic import AddTorrentsTab
from console_widget import CheckUpdatesButton, ConsoleLogOutput
from custom_labels import LEDLabel, SyncBlockLabel, UpdateLabel
from search_torrents_logic import SearchTorrentsTab
from torrent_table import TorrentSearchBar, TorrentsSelectedLabelCounter, TorrentsTable
import resources_rc
